#制定node镜像的版本
# FROM node
# 小体积的 node 镜像
FROM mhart/alpine-node:12

#声明作者
LABEL version="1.0" description="taoland-pc-next服务" by="yyt"
# RUN npm install -g nodemon
#新建文件夹
RUN mkdir /taoland
#进入到node目录下面，类似cd
WORKDIR /taoland
#移动当前目录下面的文件到taoland目录下
COPY ./frontend/. ./
COPY package.json ./
#COPY yarn.lock ./
#COPY node_modules ./node_modules
#安装依赖
#RUN yarn
RUN npm config set registry https://registry.npm.taobao.org/ 
RUN npm install

#对外暴露的端口
EXPOSE 7999
#程序启动脚本
# CMD [ "node", "./api/index.js" ]
CMD [ "npm", "run", "docker-next-start" ]
